version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: hirequotientserver
    container_name: hirequotientserver
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"

